### ISSUE TITLE
DarkSystem?

### ISSUE THREAD

**Issue by dirouc** [Apollo-SoftwareTeam/Apollo-Legacy#102]
DarkSystemis the worst solution of the multiversion, it is made by a person who fixes one error a month. There's a lot of things that you do not need. I used Apollo its clean, and now it's not like that

**Comment by dirouc** [comment]
I just started the server for the first time..
`[*] DarkSystem Set-up Wizard
[*] Language:
 Türkçe => tur
 English => eng
 简体中文 => chs
 繁體中文 => zho
 日本語 => jpn
 Русский => rus
 Italiano => ita
[?] Language (eng): eng
[*] English has been correctly selected.
Welcome to DarkSystem!
Before starting setting up your new server you have to accept the license.
DarkSystem is licensed under the GPL License,
that you can read opening the LICENSE file on this folder.

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

[?] Do you accept the License? (y/N): y
[?] Do you want to skip the set-up wizard? (y/N): y


    ______           _    _____           _
    |  _  \         | |  /  ___|         | |
    | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___
    | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \
    | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | |
    |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_|
                                 __/  |
                                 |___/         MCPE: v1.x (141)
      Fast!

      DarkSystem 5.2.0  *Skeletonhead*


<11:03:21> DarkSystem 》 INFO: Enabling Plugins...
<11:03:22> DarkSystem 》 CRITICAL: ClassNotFoundException: "Class pocketmine\command\SpawnPointCommand does not exist" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 126
<11:03:22> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
`

**Comment by dirouc** [comment]
Crashdump ```DarkSystem Crash Report Sat Dec 16 11:03:22 UTC 2017

Error: Class pocketmine\command\SpawnPointCommand does not exist
File: /src/spl/BaseClassLoader
Line: 126
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN```

**Comment by dirouc** [comment]
fixed #103

**Comment by dirouc** [comment]
And here comes 2 error

```

    ______           _    _____           _
    |  _  \         | |  /  ___|         | |
    | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___
    | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \
    | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | |
    |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_|
                                 __/  |
                                 |___/         MCPE: v1.x (141)
      Safe!

      DarkSystem 5.2.0  *Skeletonhead*


<11:12:52> DarkSystem 》 INFO: Enabling Plugins...
<11:12:53> DarkSystem 》 CRITICAL: ParseError: "syntax error, unexpected 'namespace' (T_NAMESPACE)" (EXCEPTION) in "/src/pocketmine/entity/ArmorStand" at line 12
<11:12:53> DarkSystem 》 EMERGENCY: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

```

**Comment by dirouc** [comment]
fix in #104

**Comment by dirouc** [comment]
3 error:

```
    ______           _    _____           _
    |  _  \         | |  /  ___|         | |
    | | | |__ _ _ __| | _\ `--. _   _ ___| |_ ___ _ __ ___
    | | | / _` | '__| |/ /`--. \ | | / __| __/ _ \ '_ ` _ \
    | |/ / (_| | |  |   </\__/ / |_| \__ \ ||  __/ | | | | |
    |___/ \__,_|_|  |_|\_\____/ \__, |___/\__\___|_| |_| |_|
                                 __/  |
                                 |___/         MCPE: v1.x (141)
      Fast!

      DarkSystem 5.2.0  *Skeletonhead*


<11:15:32> DarkSystem 》 INFO: Enabling Plugins...
<11:15:33> DarkSystem 》 INFO: Use openssl as AES encryption engine.
<11:15:33> DarkSystem 》 INFO: Use openssl as RSA encryption engine.
<11:15:33> DarkSystem 》 INFO: Starting Minecraft: PC server on *:22565 version 1.12.2
<11:15:33> DarkSystem 》 NOTICE: Level "world" not found

Notice: Uninitialized string offset: 1098 in C:\Users\dirouc\Desktop\Apollo-Legacy-master\src\pocketmine\nbt\NBT.php on line 419

Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$Data in C:\Users\dirouc\Desktop\Apollo-Legacy-master\src\pocketmine\level\format\generic\BaseLevelProvider.php on line 42
<11:15:33> DarkSystem 》 ERROR: Could not generate level "world": Invalid level.dat
<11:15:33> DarkSystem 》 CRITICAL: pocketmine\utils\LevelException: "Invalid level.dat" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseLevelProvider" at line 45
<11:15:33> DarkSystem 》 EMERGENCY: No default level has been loaded
<11:15:33> DarkSystem 》 INFO: Disabling Plugins...
```

**Comment by CasperVanNeck** [comment]
We aren't done yet with it

**Comment by CasperVanNeck** [comment]
Ok i think i change it to pmmp

**Comment by dirouc** [comment]
fix 3 error..
