### ISSUE TITLE
composer.json is invalid

### ISSUE THREAD

**Issue by ZizzyZizzy** [Apollo-SoftwareTeam/Apollo-Legacy#109]
composer.json from the repo (found on March 10th, 2018) is invalid. It's not a JSON file, but appears to be a .phar file of some kind.

You'll want to pull the correct file from PMMP.

**Comment by ZizzyZizzy** [comment]
Same with composer.lock

**Comment by caspervanneck** [comment]
we know about this isue

**Comment by caspervanneck** [comment]
fixt
