### ISSUE TITLE
Add me as contributor since you've accepted me as member :/

### ISSUE THREAD

**Issue by TheAz928** [Apollo-SoftwareTeam/Apollo-Legacy#57]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* SpigotPE:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in SpigotPE)

### Crashdump, backtrace or other files

* ...

**Comment by shdudwns** [comment]
You can not load old Flynn?

**Comment by Wesley-Van-Neck** [comment]
Stop spamming or ban

**Comment by TheAz928** [comment]
OK LMFAO BYE I DON'T RVEN CARE THIS FAKE SHIT 😂😂

**Comment by Wesley-Van-Neck** [comment]
ban

**Comment by Wesley-Van-Neck** [comment]
hope your happy

**Comment by TheAz928** [comment]
Your software gonna die anyway 😂

**Comment by TheAz928** [comment]
c'mon, ban me! I'm waiting to see this organization fall 😂

**Comment by Wesley-Van-Neck** [comment]
its not shut up @TheAz928 we were spigotpe

**Comment by Wesley-Van-Neck** [comment]
wow that says a guy wo dident know php very well

**Comment by TheAz928** [comment]
Lmao, SpigotPE, but fork of Nukkit or pmmp, no official stuff

**Comment by Wesley-Van-Neck** [comment]
shut up how to dose it feel your baned
