### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Apollo-SoftwareTeam/Apollo-Legacy#59]
root@ViGladios:~/gen# ./start.sh

Fatal error: Uncaught Error: Call to undefined function pocketmine\utils\stream_isatty() in /root/gen/src/pocketmine/utils/Terminal.php:61
Stack trace:
#0 /root/gen/src/pocketmine/PocketMine.php(180): pocketmine\utils\Terminal::hasFormattingCodes()
#1 {main}
  thrown in /root/gen/src/pocketmine/utils/Terminal.php on line 61
root@ViGladios:~/gen#

**Comment by Wesley-Van-Neck** [comment]
Hmmm they don't use php 7.1? @BogdanMakarchuk

**Comment by Fabiansigala** [comment]
What php do you have?

**Comment by BogdanMakarchuk** [comment]
@Wesley-Van-Neck, 7.0.3

**Comment by Wesley-Van-Neck** [comment]
Well @BogdanMakarchuk you need php7.1

**Comment by Wesley-Van-Neck** [comment]
@BogdanMakarchuk i hope it fixt now
