### ISSUE TITLE
Nukkit-Help Group Discord. [Helping, Performance, Informations]

### ISSUE THREAD

**Issue by NycuRO** [Apollo-SoftwareTeam/Apollo-Legacy#68]
Due to the fact that the Nukkit Team does not want to hear or is not interested in a Discourse Official Group for their Software, I decided to create a group, namely to "modify" the old one into a new one, better and especially for Nukkit.

Why do we need this group?

The group is made for all players, developers and the rest of the people interested or not by Nukkit.

I want Nukkit to be again a Good, Active and Useful Software for MCPE.

So, we're waiting for the group on the disagreement.

All developers have special grades, namely "Developers", and if they wish, they can also help the players with some information.

If you have problems or information or something else, you find me in a dispute.

Link: https://discordapp.com/invite/7y8WM4F

This is not an intention to promote or advertise for an action of my interest. It's just for Nukkit.

**Comment by shdudwns** [comment]
?

**Comment by NycuRO** [comment]
@shdudwns Nukkit it's one software good and better in Java. I created one Group Discord for info's , performance and good Helping. You can enter if you want 👍

**Comment by Wesley-Van-Neck** [comment]
@NycuRO its dead

**Comment by Wesley-Van-Neck** [comment]
nukkit is dead

**Comment by NycuRO** [comment]
@Wesley-Van-Neck Isn't lol.

**Comment by Wesley-Van-Neck** [comment]
yes it is the orginal poeple arent active and there api is shit
