### ISSUE TITLE
The Spigot logo has a copyright.

### ISSUE THREAD

**Issue by thebigsmileXD** [Apollo-SoftwareTeam/Apollo-Legacy#74]

**Comment by CasperVanNeck** [comment]
@thebigsmileXD we are aware off it do we changed are name and logo

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/31541947-817c9bd0-b010-11e7-879f-0483782a7218.png)

**Comment by Wesley-Van-Neck** [comment]
I knie sorry

**Comment by Wesley-Van-Neck** [comment]
Know*
