### ISSUE TITLE
Jenkins for building production phar

### ISSUE THREAD

**Issue by fengberd** [Apollo-SoftwareTeam/Apollo-Legacy#77]
### Issue description
Hello Apollo-SoftwareTeam,
We found this nice project on github,but it seems that there's no any ci-system to build production phar to users.
CircleCI requires login so it's not friendly enough.
So we add this project to our [ZXDA Public Jenkins](https://jenkins.zxda.net/job/Apollo-Legacy/).
If possible,could you use this as the official jenkins?It's good for users and your team.

### Steps to reproduce the issue
Nope.

### OS and versions
* ApolloPE: Keep updated
* PHP:PHP 7.2.0RC4 (cli) (built: Oct 26 2017 00:45:40) ( ZTS )
* Server OS:CentOS release 6.9 (Final)
* Game version: PE/Win10 (delete as appropriate)

### Plugins
FServerPacker for server auto packing

### Crashdump, backtrace or other files
Nope.

**Comment by CasperVanNeck** [comment]
@fengberd yes 👍
