### ISSUE TITLE
Multiversion?

### ISSUE THREAD

**Issue by ghost** [Apollo-SoftwareTeam/Apollo-Legacy#89]
How about making a multiversion? 1.0..1.1...1.2

**Comment by CasperVanNeck** [comment]
It's pland

**Comment by dirouc** [comment]
@CasperVanNeck How much more to wait? At least 1.1 - 1.2

**Comment by CasperVanNeck** [comment]
not long i hope

**Comment by CasperVanNeck** [comment]
its done

**Comment by dirouc** [comment]
reopen

**Comment by Icey-girl** [comment]
Well first support php 7.0 and 32bit

**Comment by FienixEC** [comment]
this software support php 7.2?
