### ISSUE TITLE
We need help converting Launguages

### ISSUE THREAD

**Issue by Fabiansigala** [Apollo-SoftwareTeam/Apollo-Legacy#91]
Anyone is able to help just send us a commit it translate the file and send it here :) if you need help finding the directory it is here 😛 [Directory!](https://github.com/Apollo-SoftwareTeam/Apollo-Legacy/blob/master/src/pocketmine/resources/apollo_eng.yml)

**Comment by CasperVanNeck** [comment]
@Fabiansigala you only do the grey line not green

**Comment by dirouc** [comment]
#99

**Comment by CasperVanNeck** [comment]
Great! thnx @dirouc

**Comment by dirouc** [comment]
Ok. Again if you need something Russian translate, tell me t.me/dirouc

**Comment by MasterDudes** [comment]
Hey @Icey-girl @Fabiansigala what languages are needed?

**Comment by MasterDudes** [comment]
Hey @Icey-girl @Fabiansigala what languages are needed?
